---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/11ty/_content/_work
  label: work
  create: documents
  match: "*.md"
upload_dir: annabrab
public_path: https://res.cloudinary.com/wommy/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
