---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: src/11ty/_data/work.json
  label: work
- type: directory
  path: src/11ty/_content/_work
  label: md
  create: documents
  match: "*.md"
  new_doc_ext: ".md"
  templates:
  - work
- type: document
  path: src/11ty/cv.md
  label: cv
- type: document
  path: src/11ty/press.md
  label: press
- type: document
  path: src/11ty/contact.md
  label: contact
upload_dir: annabrab
public_path: https://res.cloudinary.com/wommy/image/upload
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
