backend:
  name: git-gateway
  branch: develop
publish_mode: editorial_workflow
media_folder: "_static/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "pages"
    label: "Pages"
    folder: "views"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "_page"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "work"
    label: "Work"
    folder: "views/work"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "_post"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "work"}
      - {label: "Work", name: "work", widget: "image"}      
      - {label: "Title", name: "title", widget: "string"}      
      - {label: "Description", name: "description", widget: "text"}      
  - name: "press"
    label: "Press"
    folder: "views/press"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "_post"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "press"}
      - {label: "Body", name: "body", widget: "markdown"}      
