backend:
  name: git-gateway
  branch: develop
publish_mode: editorial_workflow
media_folder: "static/img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "pages"
    label: "Pages"
    folder: "views"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "_page"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "press"
    label: "Press"
    folder: "views/press"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "_post"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "press"}
      - {label: "Body", name: "body", widget: "markdown"}      
