backend:
  name: git-gateway
  branch: develop
media_folder: "_static/images/"
collections:
  - name: "work"
    label: "Work"
    folder: "work"
    create: true
    slug: "{{slug}}"
    # summary: "<img src="{{image}}" /> - {{title}}"
    fields:
      - {
        label: "Image", 
        name: "image", 
        widget: "image"
      }      
      - {
        label: "Name", 
        name: "title", 
        widget: "string"
      }      
      - {
        label: "Description", 
        name: "description", 
        widget: "text",
        required: false
      }      
